<?php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;

class CreacionSolicitudSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    { //acta #69
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'254',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'1',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);

        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'413',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'2',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'423',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'3',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'534',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'4',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'536',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'5',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'695',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'6',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:10:00',
            'n_colegiado'=>'754',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'7',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:11:00',
            'n_colegiado'=>'903',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'8',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1011',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'9',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:00:00',
            'n_colegiado'=>'1708',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'10',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
        ]);
        //acta 70
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'393',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'11',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'444',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'12',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'472',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'13',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);        
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'794',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'14',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'893',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'15',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'980',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'16',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1342',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'17',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1429',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'18',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        //acta71
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'160',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'19',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'432',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'20',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);    
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'436',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'21',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'473',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'22',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1387',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'23',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta72
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'624',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'24',
            'no_acta'=>'072',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'790',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'25',
            'no_acta'=>'072',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'957',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'26',
            'no_acta'=>'072',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'155',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'27',
            'no_acta'=>'072',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'237',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'28',
            'no_acta'=>'072',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta73
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'383',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'29',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'463',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'30',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'580',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'31',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'615',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'32',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'785',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'33',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'940',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'34',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta74
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'375',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'35',
            'no_acta'=>'074',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta75
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'225',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'36',
            'no_acta'=>'075',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
                ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'513',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'37',
            'no_acta'=>'075',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'751',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'38',
            'no_acta'=>'075',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'2151',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'39',
            'no_acta'=>'075',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta76 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'224',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'40',
            'no_acta'=>'076',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta77
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'650',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'41',
            'no_acta'=>'077',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'610',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'42',
            'no_acta'=>'077',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'685',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'43',
            'no_acta'=>'077',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'2009',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'44',
            'no_acta'=>'077',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]); 
            //acta78
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'721',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'45',
            'no_acta'=>'078',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);   
            //acta79
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'184',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'46',
            'no_acta'=>'079',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'433',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'47',
            'no_acta'=>'079',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'564',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'48',
            'no_acta'=>'079',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta80
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'825',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'49',
            'no_acta'=>'080',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1161',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'50',
            'no_acta'=>'080',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1369',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'51',
            'no_acta'=>'080',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1378',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'52',
            'no_acta'=>'080',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'4642',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'53',
            'no_acta'=>'080',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta81
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'640',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'54',
            'no_acta'=>'081',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'689',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'55',
            'no_acta'=>'081',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta82
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'680',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'56',
            'no_acta'=>'082',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1451',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'57',
            'no_acta'=>'082',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta85
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'509',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'58',
            'no_acta'=>'085',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1425',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'59',
            'no_acta'=>'085',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta87
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'671',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'60',
            'no_acta'=>'087',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
             //acta88
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'755',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'61',
            'no_acta'=>'087',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //acta89
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'419',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'62',
            'no_acta'=>'089',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'864',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'63',
            'no_acta'=>'089',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1008',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'64',
            'no_acta'=>'089',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]); 
             //acta90
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'976',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'65',
            'no_acta'=>'090',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1992',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'66',
            'no_acta'=>'090',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta91
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'814',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'67',
            'no_acta'=>'091',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1672',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'68',
            'no_acta'=>'091',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta94
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'465',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'69',
            'no_acta'=>'094',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'2775',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'70',
            'no_acta'=>'094',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta96
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'550',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'71',
            'no_acta'=>'096',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
      //acta97
            DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1064',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'72',
            'no_acta'=>'097',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
             //acta99
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'333',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'73',
            'no_acta'=>'099',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
             //acta100
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'2759',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'74',
            'no_acta'=>'0100',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'778',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'75',
            'no_acta'=>'0100',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);     
             //acta102
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'608',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'76',
            'no_acta'=>'0102',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        //acta103
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'282',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'77',
            'no_acta'=>'0103',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'882',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'78',
            'no_acta'=>'0103',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);    
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1798',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'79',
            'no_acta'=>'0103',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);    
             //acta104
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'928',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'80',
            'no_acta'=>'0104',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'951',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'81',
            'no_acta'=>'0104',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);    
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'1460',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'82',
            'no_acta'=>'0104',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);    
             //acta105
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2011-01-01 00:12:00',
            'n_colegiado'=>'140',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'83',
            'no_acta'=>'0105',
            'id_creacion'=>'1',
            'junta'=>'2011-2013'
            ]);  
            //Junta 2013/2015
            //acta1
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'3772',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'1',
            'no_acta'=>'001',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);  
            //acta4
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'511',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'2',
            'no_acta'=>'004',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1922',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'3',
            'no_acta'=>'004',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);  
            //acta5
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'594',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'4',
            'no_acta'=>'005',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta7
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'771',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'5',
            'no_acta'=>'007',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta8
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'670',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'6',
            'no_acta'=>'008',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta009
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'618',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'7',
            'no_acta'=>'009',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'798',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'8',
            'no_acta'=>'009',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1268',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'9',
            'no_acta'=>'009',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta010
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'9459',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'10',
            'no_acta'=>'010',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta011
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1359',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'11',
            'no_acta'=>'011',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta012
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'332',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'12',
            'no_acta'=>'012',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta013
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'451',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'13',
            'no_acta'=>'013',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta016
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'711',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'14',
            'no_acta'=>'016',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta017
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'331',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'15',
            'no_acta'=>'017',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'467',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'16',
            'no_acta'=>'017',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta019
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1160',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'17',
            'no_acta'=>'019',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta024
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'138',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'18',
            'no_acta'=>'024',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta025
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1367',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'19',
            'no_acta'=>'025',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta027
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'876',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'20',
            'no_acta'=>'027',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'649',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'21',
            'no_acta'=>'027',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta029
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'324',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'22',
            'no_acta'=>'029',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta031
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'4331',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'23',
            'no_acta'=>'031',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta032
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'270',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'24',
            'no_acta'=>'032',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta033
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'538',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'25',
            'no_acta'=>'033',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta039
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'5870',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'26',
            'no_acta'=>'039',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta041
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'681',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'27',
            'no_acta'=>'041',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta042
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'3522',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'28',
            'no_acta'=>'042',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta043
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'826',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'29',
            'no_acta'=>'043',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta048
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'378',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'30',
            'no_acta'=>'048',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta051
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'914',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'31',
            'no_acta'=>'051',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1001',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'32',
            'no_acta'=>'051',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta052
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'806',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'33',
            'no_acta'=>'052',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta053
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1328',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'34',
            'no_acta'=>'053',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta054
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1150',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'35',
            'no_acta'=>'054',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta056
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'422',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'36',
            'no_acta'=>'056',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta059
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'5216',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'37',
            'no_acta'=>'059',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta064
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'3363',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'38',
            'no_acta'=>'064',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta065
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'766',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'39',
            'no_acta'=>'065',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta070
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'2211',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'40',
            'no_acta'=>'070',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta071
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'919',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'41',
            'no_acta'=>'071',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta074
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'675',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'42',
            'no_acta'=>'074',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'856',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'43',
            'no_acta'=>'074',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta076
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1356',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'44',
            'no_acta'=>'076',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta080
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'674',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'45',
            'no_acta'=>'080',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
             //acta091
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1250',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'46',
            'no_acta'=>'091',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //acta095
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'699',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'47',
            'no_acta'=>'095',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'677',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'48',
            'no_acta'=>'095',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'2928',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'49',
            'no_acta'=>'095',
            'id_creacion'=>'1',
            'junta'=>'2013-2015'
            ]);
            //Junta 2015/2017
            //acta001
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'529',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'1',
            'no_acta'=>'001',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'593',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'2',
            'no_acta'=>'001',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta003
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'854',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'3',
            'no_acta'=>'003',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta004
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'590',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'4',
            'no_acta'=>'004',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta009
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'731',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'5',
            'no_acta'=>'009',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta013
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1055',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'6',
            'no_acta'=>'013',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'636',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'7',
            'no_acta'=>'013',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta036
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1358',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'8',
            'no_acta'=>'036',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta037
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'823',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'9',
            'no_acta'=>'037',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]);  
            //acta042
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'908',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'10',
            'no_acta'=>'042',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
            //acta045
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'791',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'11',
            'no_acta'=>'045',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
            //acta046
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1373',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'12',
            'no_acta'=>'046',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
            //acta047
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'2106',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'13',
            'no_acta'=>'047',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1258',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'14',
            'no_acta'=>'047',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
              //acta050
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'732',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'15',
            'no_acta'=>'050',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
              //acta055
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1004',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'16',
            'no_acta'=>'055',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta059
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'724',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'17',
            'no_acta'=>'059',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'974',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'18',
            'no_acta'=>'059',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta060
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1743',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'19',
            'no_acta'=>'060',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta062
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1569',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'20',
            'no_acta'=>'062',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta063
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1174',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'21',
            'no_acta'=>'063',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta067
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'620',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'22',
            'no_acta'=>'067',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta068
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'952',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'23',
            'no_acta'=>'068',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta076
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1490',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'24',
            'no_acta'=>'076',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta082
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'709',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'25',
            'no_acta'=>'082',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'286',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'26',
            'no_acta'=>'082',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'672',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'27',
            'no_acta'=>'082',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'702',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'28',
            'no_acta'=>'082',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
            //acta085
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'6066',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'29',
            'no_acta'=>'085',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'664',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'30',
            'no_acta'=>'085',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //acta086
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2015-01-01 00:12:00',
            'n_colegiado'=>'1575',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'31',
            'no_acta'=>'086',
            'id_creacion'=>'1',
            'junta'=>'2015-2017'
            ]); 
             //Junta 2017/2019
            //acta005
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1883',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'1',
            'no_acta'=>'005',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
            //acta007
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'717',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'2',
            'no_acta'=>'007',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
            //acta010
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1115',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'3',
            'no_acta'=>'010',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta012
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'715',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'4',
            'no_acta'=>'012',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'4144',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'5',
            'no_acta'=>'012',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
              //acta021
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1033',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'6',
            'no_acta'=>'021',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //acta025
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1588',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'7',
            'no_acta'=>'025',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //acta035
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1341',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'8',
            'no_acta'=>'035',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'2777',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'9',
            'no_acta'=>'035',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta037
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'847',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'10',
            'no_acta'=>'037',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta039
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1103',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'11',
            'no_acta'=>'039',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta041
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'803',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'12',
            'no_acta'=>'041',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta042
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1470',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'13',
            'no_acta'=>'042',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta045
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1197',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'14',
            'no_acta'=>'045',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta051
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'972',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'15',
            'no_acta'=>'051',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //acta055
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'753',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'16',
            'no_acta'=>'055',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'954',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'17',
            'no_acta'=>'055',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1853',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'18',
            'no_acta'=>'055',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta056
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1386',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'19',
            'no_acta'=>'056',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'337',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'20',
            'no_acta'=>'056',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //acta069
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'916',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'21',
            'no_acta'=>'069',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //acta073
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'829',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'22',
            'no_acta'=>'073',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //acta078
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'656',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'23',
            'no_acta'=>'078',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
             //acta088
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'622',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'24',
            'no_acta'=>'088',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'687',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'25',
            'no_acta'=>'088',
            'id_creacion'=>'1',
            'junta'=>'2017-2019'
            ]);  
                //Junta 2019/2021
            //acta006
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'792',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'1',
            'no_acta'=>'006',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
            ]);  
             //acta008
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'2675',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'2',
            'no_acta'=>'008',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
            ]);  
             //acta011
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'734',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'3',
            'no_acta'=>'011',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
            ]);  
             //acta016
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1016',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'4',
            'no_acta'=>'016',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
        ]);  
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1374',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'5',
            'no_acta'=>'016',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
            ]);  
             //acta021
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'1117',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'6',
            'no_acta'=>'021',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
            ]);  
             //acta001
        DB::table('sigecig_solicitudes_ap')->insert([
            'fecha_solicitud'=>'2013-01-01 00:12:00',
            'n_colegiado'=>'761',
            'id_estado_solicitud'=>'10',
            'id_banco'=>'1',
            'id_tipo_cuenta'=>'1',
            'no_cuenta'=>'00000-00',
            'no_solicitud'=>'7',
            'no_acta'=>'001',
            'id_creacion'=>'1',
            'junta'=>'2019-2021'
            ]);  
    }
}
