<?php

use Illuminate\Database\Seeder;

class TiposDeProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'22',
            'timbre_id'=>'1',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'30',
            'timbre_id'=>'1',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'38',
            'timbre_id'=>'1',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'27',
            'timbre_id'=>'2',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'31',
            'timbre_id'=>'2',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'39',
            'timbre_id'=>'2',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'23',
            'timbre_id'=>'3',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'32',
            'timbre_id'=>'3',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'40',
            'timbre_id'=>'3',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'25',
            'timbre_id'=>'4',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'34',
            'timbre_id'=>'4',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'41',
            'timbre_id'=>'4',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'28',
            'timbre_id'=>'5',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'36',
            'timbre_id'=>'5',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'42',
            'timbre_id'=>'5',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'24',
            'timbre_id'=>'6',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'33',
            'timbre_id'=>'6',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'43',
            'timbre_id'=>'6',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'26',
            'timbre_id'=>'7',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'35',
            'timbre_id'=>'7',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'44',
            'timbre_id'=>'7',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'29',
            'timbre_id'=>'8',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'37',
            'timbre_id'=>'8',
        ]);
        DB::table('sigecig_tipos_de_productos')->insert([
            'tipo_de_pago_id'=>'45',
            'timbre_id'=>'8',
        ]);
    }
}
